# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0002_tjsj'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tjsj',
            old_name='data',
            new_name='snsd_data',
        ),
        migrations.AddField(
            model_name='tjsj',
            name='snwd_data',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tjsj',
            name='ydl_data',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tjsj',
            name='ysl_data',
            field=models.IntegerField(default=0),
        ),
    ]
